// @vitest-environment node
/**
 * Cross-validation against jupytext as oracle.
 *
 * fixtures/*.py are committed alongside *.py.expected.ipynb generated by
 * `scripts/generate-format-fixtures.sh` (uvx jupytext). The assertions prove
 * our percent parser agrees with jupytext on cell boundaries, types,
 * contents, and ids (quoted `id="x"` marker tokens become jupytext cell
 * metadata verbatim).
 *
 * The qmd oracle requires the quarto binary (jupytext shells out to it); the
 * generation script gates on it. When *.qmd.expected.ipynb files exist they
 * are validated the same way — otherwise qmd confidence comes from the unit
 * and property suites.
 */

import { describe, it, expect } from 'vitest';
import * as fs from 'fs';
import * as path from 'path';
import { percentAdapter } from '../percent';
import { qmdAdapter } from '../qmd';

const FIXTURES = path.join(__dirname, 'fixtures');

interface OracleCell {
  cell_type: string;
  source: string | string[];
  metadata?: Record<string, unknown>;
}

function oracleCells(ipynbPath: string): OracleCell[] {
  return JSON.parse(fs.readFileSync(ipynbPath, 'utf-8')).cells;
}

const joinSource = (s: string | string[]) => (Array.isArray(s) ? s.join('') : s);

function compareAgainstOracle(
  sourcePath: string,
  adapter: typeof percentAdapter | typeof qmdAdapter
) {
  const text = fs.readFileSync(sourcePath, 'utf-8');
  const ours = adapter.parse(text);
  const oracle = oracleCells(`${sourcePath}.expected.ipynb`);

  expect(ours.cells.length).toBe(oracle.length);
  ours.cells.forEach((cell, i) => {
    const expected = oracle[i];
    // Type: oracle 'raw' maps to our markdown + percent_cell_type='raw'
    if (expected.cell_type === 'raw') {
      expect(cell.type).toBe('markdown');
      expect((cell as any)._metadata?.percent_cell_type).toBe('raw');
    } else {
      expect(cell.type).toBe(expected.cell_type);
    }
    // Content must agree exactly with jupytext's view
    expect(cell.content).toBe(joinSource(expected.source));
    // Ids: when jupytext recorded one, ours must match
    const oracleId = expected.metadata?.id;
    if (typeof oracleId === 'string') {
      expect(cell.id).toBe(oracleId);
    }
    // Marker titles jupytext parsed must be preserved in our rest-string
    const title = expected.metadata?.title;
    if (typeof title === 'string') {
      expect((cell as any)._metadata?.percent_header_rest).toContain(title);
    }
  });
}

describe('jupytext oracle: percent format', () => {
  const pyFixtures = fs
    .readdirSync(FIXTURES)
    .filter((f) => f.endsWith('.py') && fs.existsSync(path.join(FIXTURES, `${f}.expected.ipynb`)));

  it('has committed oracle fixtures', () => {
    expect(pyFixtures.length).toBeGreaterThanOrEqual(3);
  });

  for (const fixture of pyFixtures) {
    it(`agrees with jupytext on ${fixture}`, () => {
      compareAgainstOracle(path.join(FIXTURES, fixture), percentAdapter);
    });
  }

  it('agrees with jupytext on the notebook-level kernelspec (01_basic.py)', () => {
    const src = path.join(FIXTURES, '01_basic.py');
    const ours = percentAdapter.parse(fs.readFileSync(src, 'utf-8'));
    const nb = JSON.parse(fs.readFileSync(`${src}.expected.ipynb`, 'utf-8'));
    expect(ours.kernelspecName).toBe(nb.metadata.kernelspec.name);
    expect((ours.metadata.kernelspec as any).display_name).toBe(
      nb.metadata.kernelspec.display_name
    );
  });
});

describe('jupytext oracle: qmd format (only when quarto was available at generation)', () => {
  const qmdFixtures = fs
    .readdirSync(FIXTURES)
    .filter((f) => f.endsWith('.qmd') && fs.existsSync(path.join(FIXTURES, `${f}.expected.ipynb`)));

  if (qmdFixtures.length === 0) {
    it.skip('no qmd oracle fixtures generated (quarto not installed)', () => {});
  }

  for (const fixture of qmdFixtures) {
    it(`agrees with jupytext+quarto on ${fixture}`, () => {
      compareAgainstOracle(path.join(FIXTURES, fixture), qmdAdapter);
    });
  }
});
